In [1]:
#import libraries
import pandas as pd

In [2]:
#extract and view dataset
df = pd.read_excel('Bird Strikes Data.xlsx')
pd.set_option('display.max.columns', 27)
df.head(5)

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,Origin State,When: Phase of flight,Conditions: Precipitation,Remains of wildlife collected?,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,2000-11-23,Caused damage,2,US AIRWAYS*,New York,Climb,None,False,False,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,Medium,No Cloud,Unknown bird - medium,N,30736,1500.0,0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,None,2001-07-25,Caused damage,2,AMERICAN AIRLINES,Texas,Landing Roll,None,False,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0.0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,None,2001-09-14,No damage,2,BUSINESS,Louisiana,Approach,None,False,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50.0,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,2002-09-05,No damage,2,ALASKA AIRLINES,Washington,Climb,None,True,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50.0,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,None,2003-06-23,No damage,2,COMAIR AIRLINES,Virginia,Approach,None,False,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50.0,0,No

In [3]:
#viewing the datasets information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25558 entries, 0 to 25557
Data columns (total 26 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Record ID                                25558 non-null  int64
 1   Aircraft: Type                           25429 non-null  object
 2   Airport: Name                            25429 non-null  object
 3   Altitude bin                             25429 non-null  object
 4   Aircraft: Make/Model                     25558 non-null  object
 5   Wildlife: Number struck                  25429 non-null  object
 6   Wildlife: Number Struck Actual           25558 non-null  int64
 7   Effect: Impact to flight                 25429 non-null  object
 8   FlightDate                               25429 non-null  datetime64[ns]
 9   Effect: Indicated Damage                 25558 non-null  object
 10  Aircraft: Number of engines?             25291 non-null  object
 11  Aircraft: Airline/Operator               25429 non-null  object
 12  Origin State                             25109 non-null  object
 13  When: Phase of flight                    25429 non-null  object
 14  Conditions: Precipitation                25558 non-null  object
 15  Remains of wildlife collected?           25558 non-null  bool
 16  Remains of wildlife sent to Smithsonian  25558 non-null  bool
 17  Remarks                                  20787 non-null  object
 18  Wildlife: Size                           25429 non-null  object
 19  Conditions: Sky                          25558 non-null  object
 20  Wildlife: Species                        25558 non-null  object
 21  Pilot warned of birds or wildlife?       25429 non-null  object
 22  Cost: Total $                            25558 non-null  int64
 23  Feet above ground                        25429 non-null  float64
 24  Number of people injured                 25558 non-null  int64
 25  Is Aircraft Large?                       25429 non-null  object
dtypes: bool(2), datetime64[ns](1), float64(1), int64(4), object(18)
memory usage: 4.7+ MB

In [4]:
#dropping unnecessary columns
df.drop(['Record ID', 'Remarks'], axis = 1, inplace = True)
df.head(3)

,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,Origin State,When: Phase of flight,Conditions: Precipitation,Remains of wildlife collected?,Remains of wildlife sent to Smithsonian,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,2000-11-23,Caused damage,2,US AIRWAYS*,New York,Climb,None,False,False,Medium,No Cloud,Unknown bird - medium,N,30736,1500.0,0,Yes
1,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,None,2001-07-25,Caused damage,2,AMERICAN AIRLINES,Texas,Landing Roll,None,False,False,Small,Some Cloud,Rock pigeon,Y,0,0.0,0,No
2,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,None,2001-09-14,No damage,2,BUSINESS,Louisiana,Approach,None,False,False,Small,No Cloud,European starling,N,0,50.0,0,No

In [5]:
#viewing null values
df.isnull().sum()

Aircraft: Type                             129
Airport: Name                              129
Altitude bin                               129
Aircraft: Make/Model                         0
Wildlife: Number struck                    129
Wildlife: Number Struck Actual               0
Effect: Impact to flight                   129
FlightDate                                 129
Effect: Indicated Damage                     0
Aircraft: Number of engines?               267
Aircraft: Airline/Operator                 129
Origin State                               449
When: Phase of flight                      129
Conditions: Precipitation                    0
Remains of wildlife collected?               0
Remains of wildlife sent to Smithsonian      0
Wildlife: Size                             129
Conditions: Sky                              0
Wildlife: Species                            0
Pilot warned of birds or wildlife?         129
Cost: Total $                                0
Feet above ground                          129
Number of people injured                     0
Is Aircraft Large?                         129
dtype: int64

In [6]:
#dropping duplicate columns
df = df.drop_duplicates()

In [7]:
#viewing null values after dropping duplicate columns
df.isnull().sum()

Aircraft: Type                             120
Airport: Name                              120
Altitude bin                               120
Aircraft: Make/Model                         0
Wildlife: Number struck                    120
Wildlife: Number Struck Actual               0
Effect: Impact to flight                   120
FlightDate                                 120
Effect: Indicated Damage                     0
Aircraft: Number of engines?               262
Aircraft: Airline/Operator                 120
Origin State                               449
When: Phase of flight                      120
Conditions: Precipitation                    0
Remains of wildlife collected?               0
Remains of wildlife sent to Smithsonian      0
Wildlife: Size                             120
Conditions: Sky                              0
Wildlife: Species                            0
Pilot warned of birds or wildlife?         120
Cost: Total $                                0
Feet above ground                          120
Number of people injured                     0
Is Aircraft Large?                         120
dtype: int64

In [8]:
#viewing data types
df.dtypes

Aircraft: Type                                     object
Airport: Name                                      object
Altitude bin                                       object
Aircraft: Make/Model                               object
Wildlife: Number struck                            object
Wildlife: Number Struck Actual                      int64
Effect: Impact to flight                           object
FlightDate                                 datetime64[ns]
Effect: Indicated Damage                           object
Aircraft: Number of engines?                       object
Aircraft: Airline/Operator                         object
Origin State                                       object
When: Phase of flight                              object
Conditions: Precipitation                          object
Remains of wildlife collected?                       bool
Remains of wildlife sent to Smithsonian              bool
Wildlife: Size                                     object
Conditions: Sky                                    object
Wildlife: Species                                  object
Pilot warned of birds or wildlife?                 object
Cost: Total $                                       int64
Feet above ground                                 float64
Number of people injured                            int64
Is Aircraft Large?                                 object
dtype: object

In [9]:
#populating the aircraft: type column
df['Aircraft: Type'] = df['Aircraft: Type'].fillna('Airplane')

In [10]:
#viewing null values
df.isnull().sum()

Aircraft: Type                               0
Airport: Name                              120
Altitude bin                               120
Aircraft: Make/Model                         0
Wildlife: Number struck                    120
Wildlife: Number Struck Actual               0
Effect: Impact to flight                   120
FlightDate                                 120
Effect: Indicated Damage                     0
Aircraft: Number of engines?               262
Aircraft: Airline/Operator                 120
Origin State                               449
When: Phase of flight                      120
Conditions: Precipitation                    0
Remains of wildlife collected?               0
Remains of wildlife sent to Smithsonian      0
Wildlife: Size                             120
Conditions: Sky                              0
Wildlife: Species                            0
Pilot warned of birds or wildlife?         120
Cost: Total $                                0
Feet above ground                          120
Number of people injured                     0
Is Aircraft Large?                         120
dtype: int64

In [11]:
#making a new column for flight year
df['Flight Year'] = df['FlightDate'].dt.year
df

,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,Origin State,When: Phase of flight,Conditions: Precipitation,Remains of wildlife collected?,Remains of wildlife sent to Smithsonian,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?,Flight Year
0,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,2000-11-23,Caused damage,2,US AIRWAYS*,New York,Climb,None,False,False,Medium,No Cloud,Unknown bird - medium,N,30736,1500.0,0,Yes,2000.0
1,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,None,2001-07-25,Caused damage,2,AMERICAN AIRLINES,Texas,Landing Roll,None,False,False,Small,Some Cloud,Rock pigeon,Y,0,0.0,0,No,2001.0
2,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,None,2001-09-14,No damage,2,BUSINESS,Louisiana,Approach,None,False,False,Small,No Cloud,European starling,N,0,50.0,0,No,2001.0
3,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,2002-09-05,No damage,2,ALASKA AIRLINES,Washington,Climb,None,True,False,Small,Some Cloud,European starling,Y,0,50.0,0,Yes,2002.0
4,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,None,2003-06-23,No damage,2,COMAIR AIRLINES,Virginia,Approach,None,False,False,Small,No Cloud,European starling,N,0,50.0,0,No,2003.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25552,Airplane,SACRAMENTO INTL,< 1000 ft,B-737-700,1,1,None,2011-12-29,No damage,2,SOUTHWEST AIRLINES,California,Approach,None,True,True,Medium,No Cloud,Mallard,Y,0,10.0,0,Yes,2011.0
25553,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,None,2011-12-30,No damage,2,SKYWEST AIRLINES,California,Approach,Fog,False,False,Large,Overcast,Unknown bird - large,N,0,1500.0,0,No,2011.0
25554,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,None,2011-12-30,No damage,2,US AIRWAYS,Florida,Landing Roll,None,False,False,Small,Some Cloud,Tree swallow,Y,0,0.0,0,No,2011.0
25556,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,None,2011-12-31,No damage,2,DELTA AIR LINES,Michigan,Landing Roll,None,False,False,Medium,Some Cloud,Unknown bird - medium,Y,0,0.0,0,Yes,2011.0
25557,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,None,2011-12-31,Caused damage,2,XTRA AIRWAYS,Illinois,Take-off run,None,True,False,Medium,No Cloud,Red-tailed hawk,N,0,0.0,0,Yes,2011.0

In [12]:
#populating 'wildelife: number struck' column
df['Wildlife: Number struck'] = df.apply(
    lambda row: 'Over 100' if pd.isnull(row['Wildlife: Number struck']) and (row['Wildlife: Number Struck Actual']) > 100
    else '11 to 100' if pd.isnull(row['Wildlife: Number struck']) and 10 > (row['Wildlife: Number Struck Actual']) < 101
    else '2 to 10' if pd.isnull(row['Wildlife: Number struck']) and 2 > (row['Wildlife: Number Struck Actual']) < 11
    else '1' if pd.isnull(row['Wildlife: Number struck']) and (row['Wildlife: Number Struck Actual']) == 1
    else row['Wildlife: Number struck'],
    axis = 1
)

In [13]:
#viewing null values
df.isnull().sum()

Aircraft: Type                               0
Airport: Name                              120
Altitude bin                               120
Aircraft: Make/Model                         0
Wildlife: Number struck                      0
Wildlife: Number Struck Actual               0
Effect: Impact to flight                   120
FlightDate                                 120
Effect: Indicated Damage                     0
Aircraft: Number of engines?               262
Aircraft: Airline/Operator                 120
Origin State                               449
When: Phase of flight                      120
Conditions: Precipitation                    0
Remains of wildlife collected?               0
Remains of wildlife sent to Smithsonian      0
Wildlife: Size                             120
Conditions: Sky                              0
Wildlife: Species                            0
Pilot warned of birds or wildlife?         120
Cost: Total $                                0
Feet above ground                          120
Number of people injured                     0
Is Aircraft Large?                         120
Flight Year                                120
dtype: int64

In [14]:
#fixing 'pilot warned of birds or wildlife?' column
df['Pilot warned of birds or wildlife?'] = df['Pilot warned of birds or wildlife?'].replace('Y','Yes')
df['Pilot warned of birds or wildlife?'] = df['Pilot warned of birds or wildlife?'].replace('N','No')
df

,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Number of engines?,Aircraft: Airline/Operator,Origin State,When: Phase of flight,Conditions: Precipitation,Remains of wildlife collected?,Remains of wildlife sent to Smithsonian,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?,Flight Year
0,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,2000-11-23,Caused damage,2,US AIRWAYS*,New York,Climb,None,False,False,Medium,No Cloud,Unknown bird - medium,No,30736,1500.0,0,Yes,2000.0
1,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,None,2001-07-25,Caused damage,2,AMERICAN AIRLINES,Texas,Landing Roll,None,False,False,Small,Some Cloud,Rock pigeon,Yes,0,0.0,0,No,2001.0
2,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,None,2001-09-14,No damage,2,BUSINESS,Louisiana,Approach,None,False,False,Small,No Cloud,European starling,No,0,50.0,0,No,2001.0
3,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,2002-09-05,No damage,2,ALASKA AIRLINES,Washington,Climb,None,True,False,Small,Some Cloud,European starling,Yes,0,50.0,0,Yes,2002.0
4,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,None,2003-06-23,No damage,2,COMAIR AIRLINES,Virginia,Approach,None,False,False,Small,No Cloud,European starling,No,0,50.0,0,No,2003.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25552,Airplane,SACRAMENTO INTL,< 1000 ft,B-737-700,1,1,None,2011-12-29,No damage,2,SOUTHWEST AIRLINES,California,Approach,None,True,True,Medium,No Cloud,Mallard,Yes,0,10.0,0,Yes,2011.0
25553,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,None,2011-12-30,No damage,2,SKYWEST AIRLINES,California,Approach,Fog,False,False,Large,Overcast,Unknown bird - large,No,0,1500.0,0,No,2011.0
25554,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,None,2011-12-30,No damage,2,US AIRWAYS,Florida,Landing Roll,None,False,False,Small,Some Cloud,Tree swallow,Yes,0,0.0,0,No,2011.0
25556,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,None,2011-12-31,No damage,2,DELTA AIR LINES,Michigan,Landing Roll,None,False,False,Medium,Some Cloud,Unknown bird - medium,Yes,0,0.0,0,Yes,2011.0
25557,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,None,2011-12-31,Caused damage,2,XTRA AIRWAYS,Illinois,Take-off run,None,True,False,Medium,No Cloud,Red-tailed hawk,No,0,0.0,0,Yes,2011.0

In [15]:
#dropping rows with any null values
df = df.dropna()

In [16]:
#viewing null values
df.isnull().sum()

Aircraft: Type                             0
Airport: Name                              0
Altitude bin                               0
Aircraft: Make/Model                       0
Wildlife: Number struck                    0
Wildlife: Number Struck Actual             0
Effect: Impact to flight                   0
FlightDate                                 0
Effect: Indicated Damage                   0
Aircraft: Number of engines?               0
Aircraft: Airline/Operator                 0
Origin State                               0
When: Phase of flight                      0
Conditions: Precipitation                  0
Remains of wildlife collected?             0
Remains of wildlife sent to Smithsonian    0
Wildlife: Size                             0
Conditions: Sky                            0
Wildlife: Species                          0
Pilot warned of birds or wildlife?         0
Cost: Total $                              0
Feet above ground                          0
Number of people injured                   0
Is Aircraft Large?                         0
Flight Year                                0
dtype: int64

In [17]:
#loading the transformed dataframe
transformed_dataset_path = r"C:\Users\asifs\Desktop\DS Projects\Bird Strikes Data\bird_strikes_data_transformed.xlsx"
df.to_excel(transformed_dataset_path, index = False)